### ISSUE TITLE
The link of Initial D: Arcade Stage Zero and the Third-Party version may be incorrect.

### ISSUE THREAD

**Issue by arbipher** [teknogods/teknogods.github.io#150]
On compatibility page, 

`Initial D: Arcade Stage Zero` will link to https://teknogods.github.io/compatibility/IDZTP.htm
`Initial D: Arcade Stage Zero (Third-Party - SegaTools)` will link to https://teknogods.github.io/compatibility/IDZ.htm

The name `IDZTP` `IDZ` may suggest they should be swapped.

The same case is also for `Initial D: Arcade Stage Zero Ver.2`.

**Comment by EmiMidnight** [comment]
No, they're correct. TP stands for Teknoparrot in this case, because the old segatools based support came first, and not Third Party if that's what you were assuming. We did not want to remove the old profiles in case people had already set it up and did not want to reinstall. Thus, the newer ones are IDZTP etc

**Comment by arbipher** [comment]
Thanks for explaining it! I am new to TP.
